# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-Dumpvar
version:      0.02
version_from: lib/Devel/Dumpvar.pm
installdirs:  site
requires:
    File::Spec:                    0.82
    Scalar::Util:                  1.11
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
